services:
  - type: web
    name: roomivo-backend-0jyi
    env: python
    region: frankfurt
    plan: free
    branch: master
    rootDir: backend
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: REDIS_URL
        sync: false
      - key: STORAGE_ENDPOINT
        value: "https://e9e4f279f640445e67f1070fea6e8c6c.r2.cloudflarestorage.com"
      - key: STORAGE_BUCKET
        value: "rental-platform-media"
      - key: CACHE_DIR
        value: "./.cache"
      - key: PYTHONPATH
        value: "/opt/render/project/src/backend"
      - key: ALLOWED_ORIGINS
        value: "https://roomivo-frontend-0jyi.onrender.com,http://localhost:3000"
      - key: ENVIRONMENT
        value: "production"
      
      # SECRETS (Sync false tells Render not to pull these from Git, 
      # but to prompt you to paste them manually in the Dashboard)
      - key: STORAGE_ACCESS_KEY
        sync: false
      - key: STORAGE_SECRET_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: ALGORITHM
        value: "HS256"
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "10080"
